
package hotel_mg.frames;

import static hotel_mg.frames.Reservation1.nb_nights;
import static hotel_mg.frames.Reservation1.v_checkout;
import static hotel_mg.frames.Reservation1.v_id_rev;
import static hotel_mg.frames.Reservation1.v_id_room;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class Cheking_in_form extends javax.swing.JFrame {

    Connection conn=null;
    Statement st=null;
    ResultSet res=null;
    
    Date actuelle = new Date();
    DateFormat dateformate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    String date = dateformate.format(actuelle);
    
    public Cheking_in_form() {
        conn=Connexion_BD.connect_BD();
        initComponents();
        getData();
    }

    
    private void getData(){
        String req1="select g.f_name,g.last_name,g.cin,g.email,g.gsm,p_card_nmb,g.p_card_own,g.comments"
                + "  from guest g,reservation r where r.id_rev="+v_id_rev+" and g.cin=r.cin_guest";
        String req2="select type_r,view,beds,cost from room where id_room="+v_id_room;   
        
        try {
            st=conn.createStatement();
            res=st.executeQuery(req1);
            if(res.next()){
                guestname_label.setText(res.getString("f_name")+" "+res.getString("last_name"));
                CINlabel.setText(res.getString("cin"));
                email_label.setText(res.getString("email"));
                gsm_label.setText(res.getString("gsm"));
                pcardnmb_label.setText(res.getString("p_card_nmb"));
                pcardown_label.setText(res.getString("p_card_own"));
                nbnights_label.setText(""+nb_nights);
            }
            res.close();
            
            
            res=st.executeQuery(req2);
            if(res.next()){
                roomdes_label.setText("room nb "+v_id_room+"  "+res.getString("type_r")+"-"
                        +res.getString("beds")+" with a view on the "+res.getString("view"));
            }
            nbnights_label.setText(nb_nights+"");
            checkout_label.setText(v_checkout);
            cost_label.setText(res.getString("cost")+" * "+nb_nights+"= "
                    +Double.parseDouble(res.getString("cost"))*nb_nights);

         res.close();
         st.close();

        } catch (SQLException ex) {
            Logger.getLogger(Cheking_in_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        Date now=new Date();
        DateFormat form=new SimpleDateFormat("yyyy-MM-dd HH:mm");
        
        String checkdate=form.format(now);
        date_label.setText(checkdate);
         
        
        
    }
    
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelimprim = new javax.swing.JPanel();
        pcardown_label = new javax.swing.JLabel();
        guestname_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        roomdes_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nbnights_label = new javax.swing.JLabel();
        checkout_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pcardnmb_label = new javax.swing.JLabel();
        CINlabel = new javax.swing.JLabel();
        gsm_label = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        cost_label = new javax.swing.JLabel();
        imprimer_jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Check_in_Form");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panelimprim.setBackground(new java.awt.Color(255, 255, 255));
        panelimprim.setForeground(new java.awt.Color(255, 255, 255));

        pcardown_label.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N

        guestname_label.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("Identification number:");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setText("Checking out in :");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("E-mail :");

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 51));
        jLabel8.setText("Room description :");

        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("Checking in form");

        roomdes_label.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N

        email_label.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N

        jLabel13.setText("Signature");

        nbnights_label.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N

        checkout_label.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Guest full name :");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setText("Payment card owner :");

        pcardnmb_label.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N

        CINlabel.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N

        gsm_label.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setText("Number of nights :");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("GSM");

        jLabel4.setFont(new java.awt.Font("Giddyup Std", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Brotherhood hotel");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setText("Payment card number :");

        cost.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        cost.setForeground(new java.awt.Color(51, 255, 51));
        cost.setText("cost without any other charges :");

        cost_label.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N

        javax.swing.GroupLayout panelimprimLayout = new javax.swing.GroupLayout(panelimprim);
        panelimprim.setLayout(panelimprimLayout);
        panelimprimLayout.setHorizontalGroup(
            panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelimprimLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(panelimprimLayout.createSequentialGroup()
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelimprimLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelimprimLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CINlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_label)
                            .addComponent(gsm_label)
                            .addComponent(guestname_label)
                            .addGroup(panelimprimLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cost_label))
                            .addComponent(roomdes_label, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkout_label, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nbnights_label, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pcardnmb_label, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pcardown_label, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelimprimLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelimprimLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel5});

        panelimprimLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CINlabel, checkout_label, cost_label, email_label, gsm_label, guestname_label, nbnights_label, pcardnmb_label, pcardown_label, roomdes_label});

        panelimprimLayout.setVerticalGroup(
            panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelimprimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guestname_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CINlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(email_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gsm_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcardnmb_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcardown_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(roomdes_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nbnights_label))
                .addGap(18, 18, 18)
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkout_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelimprimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cost, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cost_label, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        panelimprimLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CINlabel, checkout_label, cost, cost_label, email_label, gsm_label, guestname_label, jLabel1, jLabel2, jLabel3, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, nbnights_label, pcardnmb_label, pcardown_label, roomdes_label});

        imprimer_jButton1.setText("imprimer");
        imprimer_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimer_jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelimprim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(imprimer_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelimprim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imprimer_jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimer_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimer_jButton1ActionPerformed
        printpage(panelimprim);
          if(JOptionPane.showConfirmDialog(null,"Are you sure to check in ?","",JOptionPane.YES_NO_OPTION)==0){
            try {
                st=conn.createStatement();
                    st.executeUpdate("update reservation set g_check_in='"+date.toString()+"' where id_rev="+v_id_rev);
                    System.out.println("done checkin !!");

                    res.close();
                    st.close();
                    conn.close();
                    this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(Reservation1.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_imprimer_jButton1ActionPerformed

    private void printpage(JPanel mypanel){
        
       PrinterJob job = PrinterJob.getPrinterJob();
       job.setPrintable(new Printable(){
           public int print(Graphics g, PageFormat pf, int page) throws PrinterException {

    if (page > 0) {
      return NO_SUCH_PAGE;
    } 

    Graphics2D g2d = (Graphics2D) g;
    g2d.translate(pf.getImageableX(), pf.getImageableY());
      g2d.scale(0.2,0.2);
    mypanel.paint(g2d);

    return PAGE_EXISTS;
   }
           
       });
       boolean ok = job.printDialog();
       if (ok) {
      try {
        job.print();
      } catch (PrinterException ex) {
     }
    }

    }
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cheking_in_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cheking_in_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cheking_in_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cheking_in_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cheking_in_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CINlabel;
    private javax.swing.JLabel checkout_label;
    private javax.swing.JLabel cost;
    private javax.swing.JLabel cost_label;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel gsm_label;
    private javax.swing.JLabel guestname_label;
    private javax.swing.JButton imprimer_jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nbnights_label;
    private javax.swing.JPanel panelimprim;
    private javax.swing.JLabel pcardnmb_label;
    private javax.swing.JLabel pcardown_label;
    private javax.swing.JLabel roomdes_label;
    // End of variables declaration//GEN-END:variables
}
