
package hotel_mg.frames;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Guest_info extends javax.swing.JInternalFrame {
Connection conn=null;
ResultSet res=null;
PreparedStatement st=null;
    public Guest_info() {
        conn=Connexion_BD.connect_BD();
        initComponents();
        show_guest();
    }
    
    private void show_guest(){
        try{
            st=conn.prepareStatement("select cin as CIN, f_name as 'first name',last_name as 'last name' from guest");
            res=st.executeQuery();
            guest_list.setModel(DbUtils.resultSetToTableModel(res));
 
            res.close();
            st.close();

        }catch(Exception e){
            System.out.println(e);
        }
    }

    private void find_guest(){
        
        try{
            st=conn.prepareStatement("select cin as CIN, f_name as 'first name',last_name from guest where f_name LIKE ? ");
            st.setString(1, name_field.getText()+"%");
            res=st.executeQuery();
            guest_list.setModel(DbUtils.resultSetToTableModel(res));
 
            res.close();
            st.close();
        }catch(Exception e){
            System.out.println(e);
        }
        
        
        
    }
    
    private void move_info(){
 
           try{
       int row=guest_list.getSelectedRow();
       String cin=guest_list.getModel().getValueAt(row, 0).toString();
       
            st=conn.prepareStatement("select f_name,last_name,cin,email,gsm,p_card_nmb,p_card_own from guest where cin='"+cin+"'");
            res=st.executeQuery();
            
            if (res.next()){
                f_name_field.setText(res.getString("f_name"));
                last_name_field.setText(res.getString("last_name"));
                cin_field.setText(res.getString("cin"));
                email_field.setText(res.getString("email"));
                gsm_field.setText(res.getString("gsm"));
                pcardnmb_field.setText(res.getString("p_card_nmb"));
                pcardown_field.setText(res.getString("p_card_own"));
            }


            res.close();
            st.close();
        }catch(Exception e){
            System.out.println(e);
        }
        

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        guest_list = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        update_bt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        f_name_field = new javax.swing.JTextField();
        last_name_field = new javax.swing.JTextField();
        cin_field = new javax.swing.JTextField();
        email_field = new javax.swing.JTextField();
        gsm_field = new javax.swing.JTextField();
        pcardnmb_field = new javax.swing.JTextField();
        pcardown_field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        refrech_jButton1 = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        setTitle("Guests");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("guest name");

        name_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name_fieldKeyReleased(evt);
            }
        });

        guest_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        guest_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                guest_listMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(guest_list);

        update_bt.setText("update");
        update_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btActionPerformed(evt);
            }
        });

        jLabel2.setText("first name");

        jLabel3.setText("last name");

        jLabel4.setText("cin");

        jLabel5.setText("e-mail");

        jLabel6.setText("GSM");

        jLabel7.setText("payment card number");

        jLabel8.setText("payment card owner");

        f_name_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                f_name_fieldFocusLost(evt);
            }
        });

        last_name_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                last_name_fieldFocusLost(evt);
            }
        });

        cin_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cin_fieldFocusLost(evt);
            }
        });

        email_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_fieldFocusLost(evt);
            }
        });

        gsm_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gsm_fieldFocusLost(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_mg/imgs/guest-1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(f_name_field)
                                    .addComponent(last_name_field)
                                    .addComponent(cin_field)
                                    .addComponent(email_field)
                                    .addComponent(gsm_field, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pcardnmb_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pcardown_field, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(update_bt)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(f_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(last_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cin_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(gsm_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pcardnmb_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pcardown_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update_bt)
                .addGap(28, 28, 28))
        );

        refrech_jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_mg/imgs/green_refrech.png"))); // NOI18N
        refrech_jButton1.setFocusable(false);
        refrech_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrech_jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(refrech_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(refrech_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_fieldKeyReleased
      find_guest();
    }//GEN-LAST:event_name_fieldKeyReleased

    private void guest_listMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guest_listMouseReleased
    move_info();
    update_bt.setEnabled(true);
    }//GEN-LAST:event_guest_listMouseReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
     update_bt.setEnabled(false);
    }//GEN-LAST:event_formInternalFrameOpened

      private boolean verif_all(){
        
        return jLabel12.getText().equals("")&&jLabel11.getText().equals("")&&jLabel13.getText().equals("")&& jLabel14.getText().equals("") &&
                jLabel10.getText().equals("");
    }
    private void update_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btActionPerformed
       
        if(!verif_all())
        { JOptionPane.showMessageDialog(null,"check your input !!","input  erreur",JOptionPane.ERROR_MESSAGE);
        
        }
        else{
        
        
        int row=guest_list.getSelectedRow();
        
                try{
            String req="update guest set cin='"+cin_field.getText()+"',f_name='"+f_name_field.getText()+"',last_name='"+last_name_field.getText()+
                    "',email='"+email_field.getText()+"',gsm='"+gsm_field.getText()+"',p_card_nmb='"+pcardnmb_field.getText()+
                    "',p_card_own='"+pcardown_field.getText()+"' where cin="+guest_list.getModel().getValueAt(row, 0).toString();
            
                    st=conn.prepareStatement(req);
                    
                    if(JOptionPane.showConfirmDialog(null,"you realy want to change these info ? ", "yes",JOptionPane.YES_NO_OPTION)==0){
                          st.executeUpdate();
                        JOptionPane.showMessageDialog(null, "done","",JOptionPane.INFORMATION_MESSAGE);
                    
                    }
 
            res.close();
            st.close();
            show_guest();
        }catch(Exception e){
            System.out.println(e);
        } 
        }
    }//GEN-LAST:event_update_btActionPerformed

    
    private boolean verif_number(String var){
        
        return !(var.length()!=8 ||(!var.matches("[0-9]+")));
    }

    private boolean verif_names( String var ){

    return Pattern.compile( "[0-9]" ).matcher( var).find();
}

    private boolean verifMail(String var){
                String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        return var.matches(regex);  
    }
    
    private void email_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_fieldFocusLost
                                if(!verifMail(email_field.getText())){
     jLabel13.setText("*");
     jLabel13.setFont(new Font ("Serif", Font.BOLD, 20));
     jLabel13.setForeground(java.awt.Color.red);
                }else
                      jLabel13.setText("");
    }//GEN-LAST:event_email_fieldFocusLost

    private void f_name_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_name_fieldFocusLost
                  if(verif_names(f_name_field.getText())){
     jLabel10.setText("*");
     jLabel10.setFont(new Font ("Serif", Font.BOLD, 20));
     jLabel10.setForeground(java.awt.Color.red);
                }else
                      jLabel10.setText("");
    }//GEN-LAST:event_f_name_fieldFocusLost

    private void last_name_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_last_name_fieldFocusLost
                        if(verif_names(last_name_field.getText())){
     jLabel11.setText("*");
     jLabel11.setFont(new Font ("Serif", Font.BOLD, 20));
     jLabel11.setForeground(java.awt.Color.red);
                }else
                      jLabel11.setText("");
    }//GEN-LAST:event_last_name_fieldFocusLost

    private void cin_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cin_fieldFocusLost
                      if(!verif_number(cin_field.getText())){
     jLabel12.setText("*");
     jLabel12.setFont(new Font ("Serif", Font.BOLD, 20));
     jLabel12.setForeground(java.awt.Color.red);
                }else
                      jLabel12.setText("");
    }//GEN-LAST:event_cin_fieldFocusLost

    private void gsm_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gsm_fieldFocusLost
                        if(!verif_number(gsm_field.getText())){
     jLabel14.setText("*");
     jLabel14.setFont(new Font ("Serif", Font.BOLD, 20));
     jLabel14.setForeground(java.awt.Color.red);
                }else
                      jLabel14.setText("");
    }//GEN-LAST:event_gsm_fieldFocusLost

    private void refrech_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrech_jButton1ActionPerformed
         show_guest();
   update_bt.setEnabled(false);
   setEmpty();
    }//GEN-LAST:event_refrech_jButton1ActionPerformed
    
    private void setEmpty(){
        cin_field.setText("");
        email_field.setText("");
        f_name_field.setText("");
        last_name_field.setText("");
        gsm_field.setText("");
        pcardnmb_field.setText("");
        pcardown_field.setText("");
       

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cin_field;
    private javax.swing.JTextField email_field;
    private javax.swing.JTextField f_name_field;
    private javax.swing.JTextField gsm_field;
    private javax.swing.JTable guest_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField last_name_field;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField pcardnmb_field;
    private javax.swing.JTextField pcardown_field;
    private javax.swing.JButton refrech_jButton1;
    private javax.swing.JButton update_bt;
    // End of variables declaration//GEN-END:variables
}
