
package hotel_mg.frames;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;




public class login_usr extends javax.swing.JFrame {
    
        Connection conn=null;
        ResultSet rs=null;
        PreparedStatement ps=null;
    
    public login_usr() { 
        conn=Connexion_BD.connect_BD();
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("hotel.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        usr_jTextField1 = new javax.swing.JTextField();
        pass_jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("log in ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOG IN ");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 270, 90, 30));

        usr_jTextField1.setBackground(new java.awt.Color(171, 175, 179));
        usr_jTextField1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        usr_jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usr_jTextField1.setBorder(null);
        usr_jTextField1.setCaretColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(usr_jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 220, 30));

        pass_jPasswordField1.setBackground(new java.awt.Color(171, 175, 179));
        pass_jPasswordField1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        pass_jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        pass_jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass_jPasswordField1.setBorder(null);
        pass_jPasswordField1.setCaretColor(new java.awt.Color(0, 0, 0));
        pass_jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pass_jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pass_jPasswordField1KeyTyped(evt);
            }
        });
        getContentPane().add(pass_jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 270, 220, 30));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_mg/imgs/login2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private  void check_Log(){
        String requet="select id_emp,pass_code from staff where id_emp=? and pass_code=?";
      
            try{
             ps = conn.prepareStatement(requet);
             ps.setString(1,usr_jTextField1.getText());
             ps.setString(2,pass_jPasswordField1.getText());
             rs=ps.executeQuery();
             
                 if(rs.next()){
                     Rooms_list.id_emp=usr_jTextField1.getText();
                System.out.println("ok");
                dispose();
                new Accueil().setVisible(true);
            conn.close();
            rs.close();
            ps.close();
             return;
                }
  
            }catch(Exception e){
                System.out.println(e);
            } 
             JOptionPane.showMessageDialog(this,"false input","ERROR",JOptionPane.ERROR_MESSAGE);
             pass_jPasswordField1.setText("");
            
    }
    
    private void pass_jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_jPasswordField1KeyTyped
 if (evt.getKeyChar() == '\n') {
                        check_Log();
 }
    }//GEN-LAST:event_pass_jPasswordField1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       check_Log();
    }//GEN-LAST:event_jButton1ActionPerformed

 
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_usr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_usr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_usr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_usr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_usr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pass_jPasswordField1;
    private javax.swing.JTextField usr_jTextField1;
    // End of variables declaration//GEN-END:variables
}
