package hotel_mg.frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

public class Rooms_list extends javax.swing.JInternalFrame {
    Connection conn=null;
    ResultSet res=null;
    PreparedStatement st=null;
    
    
    Date d=new Date();
    DateFormat dateformate=new SimpleDateFormat("yyyy-MM-dd") ;
    String date=dateformate.format(d);
    
    static String room_id;
    static String d_debut,d_fin;
    static String id_emp;
    
    public Rooms_list() {
        conn=Connexion_BD.connect_BD();
        initComponents();
        showRooms_list();
    }
    
    public void showRooms_list(){
        try{
            String reqet="Select id_room,type_r as room_type,beds as nb_beds,cost from room where reserved=0";
            st=conn.prepareStatement(reqet);
            res=st.executeQuery();
            room_list_table.setModel(DbUtils.resultSetToTableModel(res));
        }catch(Exception e){
            System.out.println("--->>>"+e);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        room_list_table = new javax.swing.JTable();
        add_resv_bt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        find_bt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        date_debut_jDateChooser3 = new com.toedter.calendar.JDateChooser();
        date_fin_jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        typeroom_jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        view_jComboBox2 = new javax.swing.JComboBox();
        refrech_jButton1 = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        setTitle("Rooms_list");
        setMinimumSize(new java.awt.Dimension(1130, 490));
        setPreferredSize(new java.awt.Dimension(1130, 490));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        room_list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        room_list_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                room_list_tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(room_list_table);

        add_resv_bt.setText("add reservation");
        add_resv_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_resv_btActionPerformed(evt);
            }
        });

        jLabel3.setText("to ");

        find_bt.setBackground(new java.awt.Color(204, 255, 255));
        find_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_mg/imgs/recherch-1.png"))); // NOI18N
        find_bt.setBorder(null);
        find_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_btActionPerformed(evt);
            }
        });

        jLabel1.setText("Rooms free   from ");

        date_debut_jDateChooser3.setDateFormatString("yyyy-MM-dd");

        date_fin_jDateChooser4.setDateFormatString("yyyy-MM-dd");

        jLabel2.setText(" type");

        typeroom_jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple_1-bed", "Double_large-bed", "Double_2-beds", "family_2-rooms" , "family_3-rooms","Master_Suit","Mini_Suit" }));

        jLabel4.setText("view");

        view_jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Beach", "City" }));

        refrech_jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_mg/imgs/green_refrech.png"))); // NOI18N
        refrech_jButton1.setFocusable(false);
        refrech_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrech_jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(add_resv_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_debut_jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_fin_jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typeroom_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(view_jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(find_bt))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(refrech_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refrech_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(find_bt)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(typeroom_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view_jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(date_debut_jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(date_fin_jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_resv_bt)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel3});

        typeroom_jComboBox1.setSelectedIndex(0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()); 
    private void add_resv_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_resv_btActionPerformed
        String d_b="";
        String d_f="";
           try{
                   d_b=sdf.format(date_debut_jDateChooser3.getDate());
                   d_f =sdf.format(date_fin_jDateChooser4.getDate());
           }catch(Exception e){}
                 
       if(d_b.equals("") || d_f.equals("")) {
            JOptionPane.showMessageDialog(null, "choose reservation dates first !!");
            
        }else{
           if(d_b.compareTo(d_f)>0||d_b.compareTo(date)<0||d_f.compareTo(date)<0){
               JOptionPane.showMessageDialog(null, "must verif dates !!","date input ivalide",JOptionPane.ERROR_MESSAGE);
               return;
           }
            d_debut=d_b;
            d_fin=d_f;
            int row=room_list_table.getSelectedRow();
            room_id=room_list_table.getModel().getValueAt(row,0).toString();
            
            System.out.println("got dates as : d_begin= "+d_debut+" d_end= "+d_fin);
        
        Add_reservation fen_add_resv=new Add_reservation();
        fen_add_resv.setVisible(true);
        }
    }//GEN-LAST:event_add_resv_btActionPerformed

    private void room_list_tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_room_list_tableMouseReleased
    add_resv_bt.setEnabled(true);
    }//GEN-LAST:event_room_list_tableMouseReleased

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
           add_resv_bt.setEnabled(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void find_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_btActionPerformed
        String d_b="";
        String d_f="";
           try{
                   d_b=sdf.format(date_debut_jDateChooser3.getDate());
                   d_f =sdf.format(date_fin_jDateChooser4.getDate());
           }catch(Exception e){
               
           }
                 
       if(d_b.equals("") || d_f.equals("")) {
            JOptionPane.showMessageDialog(null, "choose reservation dates first !!");
            
        }else{
           if(d_b.compareTo(d_f)>0||d_b.compareTo(date)<0||d_f.compareTo(date)<0){
               JOptionPane.showMessageDialog(null, "must verif dates !!","date input ivalide",JOptionPane.ERROR_MESSAGE);
               return;
           }else{
        String req="select DISTINCT r.id_room,r.type_r as room_type,r.beds as nb_beds,r.cost from room r, reservation res where"
        + " (r.reserved=0 || (r.id_room=res.id_room and( res.d_begin> ? or res.d_end< ?))) and r.type_r=? and r.beds=? and r.view=?" ;
        try {
            st=conn.prepareStatement(req);

            /* st.setString(1,date_debut_jTextField1.getText());
            st.setString(2,date_fin_jTextField2.getText());*/
            String var=(String)typeroom_jComboBox1.getSelectedItem();
            String type=var.substring(0,var.indexOf("_"));
            String nbbeds=var.substring(var.indexOf("_")+1);
            System.out.println("type= "+type+" ----- nb beds= "+nbbeds);
            st.setString(1,((JTextField) date_debut_jDateChooser3.getDateEditor().getUiComponent()).getText());
            st.setString(2,((JTextField) date_fin_jDateChooser4.getDateEditor().getUiComponent()).getText());
            st.setString(3,type);
            st.setString(4,nbbeds);
            st.setString(5,(String)view_jComboBox2.getSelectedItem());

            res=st.executeQuery();
            room_list_table.setModel(DbUtils.resultSetToTableModel(res));

        } catch (SQLException ex) {
            Logger.getLogger(Rooms_list.class.getName()).log(Level.SEVERE, null, ex);
        }
        add_resv_bt.setEnabled(false);
           }
       }
    }//GEN-LAST:event_find_btActionPerformed

    private void refrech_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrech_jButton1ActionPerformed
       showRooms_list();
        add_resv_bt.setEnabled(false);
    }//GEN-LAST:event_refrech_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_resv_bt;
    private com.toedter.calendar.JDateChooser date_debut_jDateChooser3;
    private com.toedter.calendar.JDateChooser date_fin_jDateChooser4;
    private javax.swing.JButton find_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refrech_jButton1;
    private javax.swing.JTable room_list_table;
    private javax.swing.JComboBox typeroom_jComboBox1;
    private javax.swing.JComboBox view_jComboBox2;
    // End of variables declaration//GEN-END:variables
}
